Of course, I need to remove the old and fat PDF too!
 /usr/bin/git push origin gh-pages
  remote: error: Trace: 9b52ad0ca7b47a0a9a158a1c688696cb2a68bc64e8c3de437df994d35771e4a6
  remote: error: See https://gh.io/lfs for more information.
  remote: error: File volumes/fat_slides.pdf is 108.91 MB; this exceeds GitHub's file size limit of 100.00 MB
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
  To https://github.com/gounthar/cours-devops-docker.git
   ! [remote rejected] gh-pages -> gh-pages (pre-receive hook declined)
  error: failed to push some refs to 'https://github.com/gounthar/cours-devops-docker.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"